name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: eu-north-1
  AWS_ACCOUNT_ID: 485701710361

jobs:
  build-test-and-deploy:
    name: Build, Test and Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Only run on main branch pushes
    
    permissions:
      id-token: write   # Required for OIDC
      contents: write   # Required for creating tags
      actions: read     # Required for checkout
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for versioning
          
      - name: Generate version number
        id: version
        run: |
          # Get the latest tag, default to v0.0.0 if none exists
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $LATEST_TAG"
          
          # Extract version numbers (remove 'v' prefix if present)
          VERSION=${LATEST_TAG#v}
          
          # Split version into parts
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          
          # Increment patch version
          PATCH=$((PATCH + 1))
          
          # Create new version
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          NEW_TAG="v$NEW_VERSION"
          
          echo "New version: $NEW_VERSION"
          echo "New tag: $NEW_TAG"
          
          # Set outputs for other steps
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "tag=$NEW_TAG" >> $GITHUB_OUTPUT
          echo "build_date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
        
      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/robotics-cicd-github-actions-role
          role-session-name: GitHubActions-CI-CD-Demo
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Verify AWS identity
        run: |
          echo "AWS Account ID: $(aws sts get-caller-identity --query Account --output text)"
          echo "AWS Region: ${{ env.AWS_REGION }}"
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker image
        env:
          APP_VERSION: ${{ steps.version.outputs.version }}
          BUILD_DATE: ${{ steps.version.outputs.build_date }}
        run: |
          docker build \
            --build-arg APP_VERSION=$APP_VERSION \
            --build-arg BUILD_DATE="$BUILD_DATE" \
            -t robotics-cicd-demo:latest \
            -t robotics-cicd-demo:$APP_VERSION \
            ./app
          echo "Docker image built successfully with version $APP_VERSION"
          
      - name: Test Docker image
        run: |
          # Start container in background
          docker run -d -p 8080:8080 --name test-container robotics-cicd-demo:latest
          
          # Wait for container to start
          sleep 10
          
          # Test endpoints
          echo "Testing main endpoint..."
          curl -f http://localhost:8080/ || exit 1
          
          echo "Testing health endpoint..."
          curl -f http://localhost:8080/health || exit 1
          
          echo "Testing version endpoint..."
          curl -f http://localhost:8080/version || exit 1
          
          # Clean up
          docker stop test-container
          docker rm test-container
          
          echo "All tests passed!"
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: robotics-cicd
          APP_VERSION: ${{ steps.version.outputs.version }}
          BUILD_DATE: ${{ steps.version.outputs.build_date }}
        run: |
          # Build image with version and ECR tags
          docker build \
            --build-arg APP_VERSION=$APP_VERSION \
            --build-arg BUILD_DATE="$BUILD_DATE" \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$APP_VERSION \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:latest \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }} \
            ./app
          
          # Push all tags to ECR
          echo "Pushing images to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$APP_VERSION
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}
          
          echo "Images pushed successfully!"
          echo "Version tag: $ECR_REGISTRY/$ECR_REPOSITORY:$APP_VERSION"
          echo "Latest tag: $ECR_REGISTRY/$ECR_REPOSITORY:latest"
          echo "Commit tag: $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}"
          
      - name: Create Git tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag ${{ steps.version.outputs.tag }}
          git push origin ${{ steps.version.outputs.tag }}
          
      - name: Update ECS task definition with new image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: robotics-cicd
          IMAGE_TAG: ${{ steps.version.outputs.version }}
        run: |
          # Create new task definition with updated image URI
          NEW_IMAGE_URI="$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          echo "Updating task definition with image: $NEW_IMAGE_URI"
          
          # Update the task definition JSON with new image URI
          sed "s|\"image\": \"[^\"]*\"|\"image\": \"$NEW_IMAGE_URI\"|g" ecs/task-definition.json > ecs/updated-task-definition.json
          
          echo "Updated task definition:"
          cat ecs/updated-task-definition.json | jq '.containerDefinitions[0].image'
      
      - name: Register new ECS task definition
        run: |
          TASK_DEFINITION_ARN=$(aws ecs register-task-definition \
            --region ${{ env.AWS_REGION }} \
            --cli-input-json file://ecs/updated-task-definition.json \
            --query 'taskDefinition.taskDefinitionArn' \
            --output text)
          
          echo "Registered new task definition: $TASK_DEFINITION_ARN"
          echo "TASK_DEFINITION_ARN=$TASK_DEFINITION_ARN" >> $GITHUB_ENV
      
      - name: Update ECS service
        env:
          CLUSTER_NAME: robotics-cicd-demo-cluster
          SERVICE_NAME: robotics-cicd-demo-service
        run: |
          echo "Updating ECS service: $SERVICE_NAME in cluster: $CLUSTER_NAME"
          
          aws ecs update-service \
            --region ${{ env.AWS_REGION }} \
            --cluster $CLUSTER_NAME \
            --service $SERVICE_NAME \
            --task-definition $TASK_DEFINITION_ARN \
            --force-new-deployment
          
          echo "ECS service update initiated"
      
      - name: Wait for deployment to complete
        env:
          CLUSTER_NAME: robotics-cicd-demo-cluster
          SERVICE_NAME: robotics-cicd-demo-service
        run: |
          echo "Waiting for deployment to complete (this may take a few minutes)..."
          
          aws ecs wait services-stable \
            --region ${{ env.AWS_REGION }} \
            --cluster $CLUSTER_NAME \
            --services $SERVICE_NAME
          
          echo "Deployment completed successfully!"
      
      - name: Get service endpoint
        env:
          CLUSTER_NAME: robotics-cicd-demo-cluster
          SERVICE_NAME: robotics-cicd-demo-service
        run: |
          echo "Getting public IP address of the running task..."
          
          # Get task ARN
          TASK_ARN=$(aws ecs list-tasks \
            --region ${{ env.AWS_REGION }} \
            --cluster $CLUSTER_NAME \
            --service-name $SERVICE_NAME \
            --query 'taskArns[0]' \
            --output text)
          
          if [ "$TASK_ARN" != "None" ] && [ -n "$TASK_ARN" ]; then
            # Get ENI ID from task
            ENI_ID=$(aws ecs describe-tasks \
              --region ${{ env.AWS_REGION }} \
              --cluster $CLUSTER_NAME \
              --tasks $TASK_ARN \
              --query 'tasks[0].attachments[0].details[?name==`networkInterfaceId`].value' \
              --output text)
            
            if [ -n "$ENI_ID" ]; then
              # Get public IP from ENI
              PUBLIC_IP=$(aws ec2 describe-network-interfaces \
                --region ${{ env.AWS_REGION }} \
                --network-interface-ids $ENI_ID \
                --query 'NetworkInterfaces[0].Association.PublicIp' \
                --output text)
              
              if [ -n "$PUBLIC_IP" ] && [ "$PUBLIC_IP" != "None" ]; then
                echo "=========================================="
                echo "🚀 Deployment completed successfully!"
                echo "Application is accessible at:"
                echo "Main endpoint:    http://$PUBLIC_IP:8080/"
                echo "Health endpoint:  http://$PUBLIC_IP:8080/health"
                echo "Version endpoint: http://$PUBLIC_IP:8080/version"
                echo "=========================================="
              fi
            fi
          fi

  test-only:
    name: Test Only (PR)
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'  # Only run on pull requests
    
    permissions:
      contents: read    # Required for checkout
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker image
        run: |
          docker build \
            --build-arg APP_VERSION=test \
            --build-arg BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
            -t robotics-cicd-demo:test \
            ./app
          echo "Docker image built successfully for testing"
          
      - name: Test Docker image
        run: |
          # Start container in background
          docker run -d -p 8080:8080 --name test-container robotics-cicd-demo:test
          
          # Wait for container to start
          sleep 10
          
          # Test endpoints
          echo "Testing main endpoint..."
          curl -f http://localhost:8080/ || exit 1
          
          echo "Testing health endpoint..."
          curl -f http://localhost:8080/health || exit 1
          
          echo "Testing version endpoint..."
          curl -f http://localhost:8080/version || exit 1
          
          # Clean up
          docker stop test-container
          docker rm test-container
          
          echo "All tests passed!"
